### ISSUE TITLE
Error creating a new record

### ISSUE THREAD

**Issue by zifiul** [adurc/exposure-react-admin#2]
When we create a new record, the exposure return the next error:

**Cannot return null for non-nullable field Mutation.createOrganization.**

Example:

![image](https://user-images.githubusercontent.com/25861581/102454420-44b82180-403e-11eb-8e30-e4905c2d1d12.png)

**Comment by bernatvadell** [comment]
Hi @zifiul 

I've fixed this in version 0.0.8

Please update to @adurc/exposure-react-admin@0.0.8
