### ISSUE TITLE
Exposure not aply sort order

### ISSUE THREAD

**Issue by zifiul** [adurc/exposure-react-admin#3]
When we order by one field, the exposure not apply it.

Example:

![image](https://user-images.githubusercontent.com/25861581/102455141-5ea63400-403f-11eb-8bbc-db78968f093b.png)

**Comment by bernatvadell** [comment]
It is not a problem of exposure, in this case, as we only have one driver, I suspect that you are the SQL Server driver. I also add the test in the driver and tell you things.

**Comment by bernatvadell** [comment]
Hi @zifiul,

Im published a new version of package: 

- @adurc/driver-mssql@0.0.4  
- @adurc/exposure-react-admin@0.0.7

Please update it and send me logs.

Thanks!

**Comment by bernatvadell** [comment]
HI @zifiul 

I've fixed issue, it was on the driver side. If you install the version @adurc /driver-mssql@0.0.5 you should see the problem corrected.

Thanks for u report
