### ISSUE TITLE
Error creating new record in join table

### ISSUE THREAD

**Issue by zifiul** [adurc/exposure-react-admin#6]
When we create a new record in a SQL join table, the exposure doesn't identify the columns. the message is 

**Unknown argument \"user_id\" on field \"Mutation.createUserAgency\"
Unknown argument \"agency_id\" on field \"Mutation.createUserAgency\".**

Example:

![image](https://user-images.githubusercontent.com/25861581/102614736-10735c80-4135-11eb-9360-dcb6f963b6e9.png)

**Comment by bernatvadell** [comment]
Hi Alvaro

It's correct.

React Admin always works with "id" field. That is why the exposure layer has removed your two primary keys and has serialized them in a single id field.

React Admin will send the serialized id and will retrieve the original ids  and do the registration correctly.

If you want to test this, you need to construct the id field as follows:

```javascript
Buffer.from('<user_id>#<agency_id>').toString('base64')
```
